yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "next-pwa@^3.1.5":
    dependencies:
      webpack: ">=4.0.0"
  "eslint-module-utils@*":
    dependencies:
      eslint-import-resolver-node: "*"
